### ISSUE TITLE
Strange error on Linux Mint

### ISSUE THREAD

**Issue by ra4king** [riven8192/LibStruct#5]
java.lang.IllegalStateException: pointer too big to fit in compressed pointer (addressable memory is 16 GB)
	at net.indiespot.struct.runtime.StructMemory.pointer2handle(StructMemory.java:200)
	at net.indiespot.struct.runtime.StructThreadLocalStack.createThreadLocalStack(StructThreadLocalStack.java:41)
	at net.indiespot.struct.runtime.StructThreadLocalStack.getStack(StructThreadLocalStack.java:19)
	at net.indiespot.struct.runtime.StructThreadLocalStack.saveStack(StructThreadLocalStack.java:10)

Using the simplest demo throws this error.

**Comment by riven8192** [comment]
It seems ByteBuffer.allocateDirect() returns buffers with a memory address that is >16G in virtual memory, on your system. Does the system actually have >16GB physical memory?

**Comment by ra4king** [comment]
No this system has 8GB of RAM.

**Comment by riven8192** [comment]
What does this print? It allocates ~2GB. If the addresses are increasing, I can establish a 'base' address and subtract that from each pointer, although it will incur some overhead for each and every memory access.

```java
List<ByteBuffer> buffers = new ArrayList<>();

for(int i=0; i<64; i++)
   buffers.add(ByteBuffer.allocateDirect(1024*1024*(i+1)));

for(ByteBuffer buffer: buffers)   
   System.out.println(StructUnsafe.getBufferBaseAddress(buffer));
```

**Comment by riven8192** [comment]
Can you pull the latest revision and pass the following JVM parameters?
```
-DLibStruct.SAFETY_FIRST=true
-DLibStruct.MEMORY_BASE_OFFSET=true
```

**Comment by riven8192** [comment]
LibStruct is now fully 64 bit enabled - all struct pointers are 64 bit. Support for struct-embedded-primitive-arrays has been disabled for the time being.
