### ISSUE TITLE
merge?

### ISSUE THREAD

**Issue by jasonnn** [riven8192/LibStruct#7]
Would you be interested in merging the gradle build setup I've been working on [here](https://github.com/jasonnn/LibStruct/tree/gradle) ? I think having a build system would make curious programmers more likely to clone your project.

**Comment by riven8192** [comment]
LibStruct was completely rewritten in the last few days, so you should bring your fork up to date first. Having said that, build tools like maven, gradle and what-not usually raise the bar to adoption, for the majority of developers.

**Comment by jasonnn** [comment]
Merging/rebasing is proving to be difficult so it may take me a little while to get it up to date. Before i begin , do you have any issues with the module structure/moving inner struct test classes to their own files/anything else?

**Comment by riven8192** [comment]
The main issue is that with your support for gradle littered the project with tiny gradle related files. I'm not sure why the designers of gradle thought this was a good design. I prefer to keep LibStruct nice and tidy. LibStruct is in a rough state after the rewrite, so big cleanups are coming up. Are you sure you want to keep maintaining your fork, while LibStruct is refactored significantly with every iteration? Or would it be less work to simply start over once the dust has settled?

I simply cannot spend too much time on making LibStruct a community effort - the code quality is currently rather poor - the focus is on fixing issues that people run into (like lack of full 64 bit support), but anything else ends up at the bottom of the todo-list.

**Comment by jasonnn** [comment]
I think ill hold off.
