### ISSUE TITLE
Another IllegalStateException

### ISSUE THREAD

**Issue by ra4king** [riven8192/LibStruct#8]
The log:
http://pastebin.com/em6y98W1

The code:
https://github.com/ra4king/OpenGL-Worlds
https://github.com/ra4king/LWJGL-OpenGL-Utils

**Comment by riven8192** [comment]
please update to the latest revision first. i'm not debugging against your fork btw, so please test with the master branch in my repository.

**Comment by ra4king** [comment]
My fork was fully updated with your master, and I haven't made any changes that would affect this. However, I have updated with a new pastebin link.

**Comment by riven8192** [comment]
Please push your dependencies.

**Comment by riven8192** [comment]
Fixed, see commit. Please turn Matrix3 & Matrix4 structs again, as you're still using them as such, making your current version crash the bytecode transformer.

**Comment by ra4king** [comment]
Thanks for the fix Riven, I knew it was an issue with interfaces!

I have fixed all locations of Matrix3/4 usage as structs into non-structs. I have not made them structs anymore as I really was not about to rewrite those two classes with 9/16 float variables....
I have deleted those reset methods... useless anyway as set(float) exists.

Huh, it compiles without warnings here on an Nvidia card with the latest drivers. That's very strange those replies say GLSL structs are not supported as vertex inputs! It has worked here for the past year that I've had this shader! I've changed it to be compliant though.

**Comment by riven8192** [comment]
"I have not made them structs anymore as I really was not about to rewrite those two classes with 9/16 float variables...."

But... that's why I added embedded arrays for you again...
```
@StructField(elements=16) public float[] arr;
```

**Comment by ra4king** [comment]
You are the best as usual.

**Comment by ra4king** [comment]
Matrix3/4 are now structs again and it works beautifully. Thanks for your work.
