### ISSUE TITLE
Automatic call to toString() when concatenating struct

### ISSUE THREAD

**Issue by ra4king** [riven8192/LibStruct#9]
Currently if I concatenate a struct in a string, I get an UnsupportedCallsiteException. Is it possible to detect these concatenations to StringBuilder and use the struct's toString() instead?

**Comment by riven8192** [comment]
The struct class is not guaranteed to have a toString() method.

**Comment by ra4king** [comment]
Ah I was thinking of calling Object's toString() when one doesn't exist but I realize now that there is no instance at all... how about a default toString() printing the Struct's name and address when one doesn't exist? "MyStruct@123456789"

**Comment by riven8192** [comment]
Structs are typeless, so I can't even print a type name. What is more important however, is that if I were to add support for 'stringifiers' for StringBuilder, people assume System.out.println(myStruct) ought to work too. List.add(myStruct) is next. People have to grasp that struct pointers are nothing like object references. They are incompatible. My position is to 'fail fast', not introduce a confusing grey area of partial, hacky support that eventually nobody will appreciate.

**Comment by riven8192** [comment]
As for the implementation: with 64 bit struct pointers I had to deal with localvar expansion. The complexity increased exponentially. Stringifying structs will require localvar narrowing, which will increase complexity yet again. In the previous 32 bit version there was limited support for stringification, where I could only stringify the last 4 parameters of a method. With the current 64 bit version that means I can (in theory) stringify only 2. Explain that to... anybody.

**Comment by ra4king** [comment]
Ah, I see the potential issues now.... never mind.
